
export const frontendCertificates = [
  { src: "https://imgur.com/Fb8rm2I.jpg", alt: "HTML y CSS" },
  { src: "https://i.imgur.com/pDrWL9x.png", alt: "Mobile First" },
  { src: "https://i.imgur.com/ue8BsCN.png", alt: "Frontend Developer" },
  { src: "https://imgur.com/O2XSbDM.png", alt: "Manejo del DOM" },
  { src: "https://i.imgur.com/4YPe4kt.png", alt: "Maquetación" },
  { src: "https://i.imgur.com/etLsnb7.png", alt: "CSS Grid básico" },
  { src: "https://i.imgur.com/cimGs3c.png", alt: "Manejo del color" },
  { src: "https://i.imgur.com/qQURlMD.png", alt: "Diseño" },
  { src: "https://i.imgur.com/1y5lpPF.png", alt: "Diseño para programadores" },
  { src: "https://i.imgur.com/SeE67br.png", alt: "Figma" },
  { src: "https://i.imgur.com/B742hic.png", alt: "Grid Layout" },
  { src: "https://i.imgur.com/rB8EPS4.png", alt: "Javascript" },
  { src: "https://imgur.com/UhBfcQv.png", alt: "Taller practico de JavaScript: Matematicas y estadistica basica" },
  { src: "https://i.imgur.com/EgB7GKC.jpg", alt: "Tailwind, Vite y React" },
  { src: "https://imgur.com/swYSZkg.png", alt: "Programacion orientada a objetos en Javascript - basico" },
  { src: "https://imgur.com/IK8HRxZ.png", alt: "Programacion orientada a objetos en Javascript - Intermedio" },
  { src: "https://imgur.com/2EwaDih.png", alt: "Introduccion a empaquetadores" },
  { src: "https://imgur.com/2xgYFF0.png", alt: "NPM: Gestión de paquetes y dependencias en JavaScript" },
  { src: "https://i.imgur.com/K9P3xCD.jpg", alt: "Typescript" },
  { src: "https://imgur.com/T5yWnEF.png", alt: "Typescript: Programacion orientada a objetos y asincronismo" },
  { src: "https://imgur.com/SzVWlqC.png", alt: "Debugging con Chrome devtools" },
  { src: "https://i.imgur.com/6LafKIq.jpg", alt: "React Profesional" },
]